export const GET_ACTIVITY = "GET_ACTIVITY";

export const SET_LIMIT_VALUE = "SET_LIMIT_VALUE";

export const SET_INCLUDE_MUTUAL_VALUE = "SET_INCLUDE_MUTUAL_VALUE";

export const SET_INCLUDE_PHOTO_VALUE = "SET_INCLUDE_PHOTO_VALUE";

export const SET_INVITATION_MSG = "SET_INVITATION_MSG";

export const SET_DISPLAY_VALUE = "SET_DISPLAY_VALUE";
